import React, { useEffect, useState } from "react"
import { RefreshCw, Sparkles } from "lucide-react"
import { Button } from "@/shared/components/ui/button"
import { useAuthStore } from "@/shared/store/useAuthStore"
import { apiErrorMessage, identityApi } from "../api/identityApi"

export const TrustScoreCard: React.FC = () => {
  const user = useAuthStore(state => state.user)
  const [score, setScore] = useState<number | null>(user?.trustScore ?? null)
  const [error, setError] = useState("")
  const [loading, setLoading] = useState(false)
  const load = async () => {
    if (!user) return
    setLoading(true); setError("")
    try { const { data } = await identityApi.getTrustScore(user.id); setScore(data.trustScore ?? data.score) }
    catch (requestError) { setError(apiErrorMessage(requestError)) } finally { setLoading(false) }
  }
  useEffect(() => { void load() }, [user?.id])
  if (!user) return null
  return <section className="rounded-xl border border-emerald-500/20 bg-emerald-950/10 p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-mono uppercase tracking-wider text-emerald-500"><Sparkles className="h-4 w-4" />Trust score</div><p className="mt-2 text-3xl font-bold text-emerald-500">{score ?? "—"}<span className="text-sm text-muted-foreground"> / 100</span></p><p className="mt-1 text-xs text-muted-foreground">Generated by protected backend trust-ledger rules.</p></div><Button variant="outline" size="icon" type="button" onClick={() => void load()} disabled={loading} aria-label="Refresh trust score"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} /></Button></div>{error && <p role="alert" className="mt-3 text-xs text-destructive">{error}</p>}</section>
}
