<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\RentaTool.Shared.Kernel\RentaTool.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\RentaTool.Shared.Infrastructure\RentaTool.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
