from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict
from pydantic import BaseModel, Field

from src.ai_service.agents.domain_models import InspectionSnapshot


class PlanStepStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"


class DisputeTargetAgent(str, Enum):
    PLANNER_AGENT = "PLANNER_AGENT"
    DOMAIN_ANALYSIS_AGENT = "DOMAIN_ANALYSIS_AGENT"
    ACTION_AGENT = "ACTION_AGENT"
    VALIDATION_AGENT = "VALIDATION_AGENT"
    HUMAN_OPERATIONS = "HUMAN_OPERATIONS"


class WorkflowResolutionState(str, Enum):
    INITIALIZED = "INITIALIZED"
    PLAN_GENERATED = "PLAN_GENERATED"
    UNDER_DOMAIN_ANALYSIS = "UNDER_DOMAIN_ANALYSIS"
    UNDER_COST_ESTIMATION = "UNDER_COST_ESTIMATION"
    UNDER_SAFETY_AUDIT = "UNDER_SAFETY_AUDIT"
    PENDING_STAFF_APPROVAL = "PendingStaffApproval"
    APPROVED = "Approved"
    REVISED = "Revised"
    REJECTED = "Rejected"
    SETTLED = "Settled"


class PlanStep(BaseModel):
    """An individual execution milestone within the dispute resolution graph."""
    step_id: str = Field(..., description="Unique step identifier (e.g. STEP_01_BASELINES)")
    step_name: str = Field(..., description="Human-readable title of the step")
    target_agent: DisputeTargetAgent = Field(..., description="Agent responsible for executing this step")
    status: PlanStepStatus = Field(default=PlanStepStatus.PENDING)
    description: str = Field(..., description="Detailed instructions for the target agent")
    output_summary: Optional[str] = Field(default=None, description="Summary of outcome once completed")
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None


class DisputePlan(BaseModel):
    """Full sequential plan generated by the Coordinator / Planner Agent."""
    plan_id: str = Field(..., description="Unique plan identifier")
    claim_id: str = Field(..., description="Dispute claim identifier")
    booking_id: str = Field(..., description="Booking associated with the dispute")
    equipment_id: str = Field(..., description="Equipment unit under dispute")
    steps: List[PlanStep] = Field(default_factory=list)
    current_step_index: int = Field(default=0, ge=0)
    plan_summary: str = Field(..., description="High-level tactical plan overview")
    estimated_duration_seconds: float = Field(default=30.0, ge=0.0)


class DisputeContext(BaseModel):
    """Input payload to start a dispute resolution workflow."""
    claim_id: str
    booking_id: str
    equipment_id: str
    equipment_title: str
    category_name: str
    daily_rate: float = Field(..., gt=0)
    replacement_value: float = Field(..., gt=0)
    security_deposit_amount: float = Field(..., gt=0)
    dispute_description: str = Field(..., description="Owner's statement of observed damage")
    renter_id: str
    owner_id: str
    pre_rental_inspection: InspectionSnapshot
    post_rental_inspection: InspectionSnapshot


class ArbitrationDossier(BaseModel):
    """Synthesized dossier compiled by the Planner for human operations staff review."""
    claim_id: str
    booking_id: str
    equipment_title: str
    category_name: str
    dispute_reason: str
    pre_rental_condition_summary: str
    post_rental_condition_summary: str
    damage_classification: str
    severity_score: float
    affected_components: List[str]
    proposed_deduction: float
    security_deposit_cap: float
    recommended_owner_payout: float
    recommended_renter_refund: float
    human_action_prompt: str = (
        "Please review photographic condition evidence and AI deduction breakdown. "
        "Select [Approve], [Revise], or [Reject] to complete escrow disbursement."
    )
    generated_at_utc: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class DisputeWorkflowState(TypedDict, total=False):
    """
    Durable execution state dictionary passed across LangGraph nodes.
    Supports persistent serialization and pause at PendingStaffApproval.
    """
    claim_id: str
    booking_id: str
    equipment_id: str
    equipment_title: str
    category_name: str
    daily_rate: float
    replacement_value: float
    security_deposit_amount: float
    dispute_description: str
    renter_id: str
    owner_id: str

    pre_rental_inspection: Dict[str, Any]
    post_rental_inspection: Dict[str, Any]

    plan: Dict[str, Any]
    current_step_index: int
    resolution_state: str

    # Agent Output Slots
    domain_analysis_result: Optional[Dict[str, Any]]
    is_structural_damage: bool
    damage_category: str

    proposed_deduction: float
    wear_factor_deduction: float
    validation_passed: bool
    validation_notes: Optional[str]

    # Human-in-the-Loop Arbitration Breakpoint
    is_halted_for_human_approval: bool
    human_review_decision: Optional[str]  # "Approve", "Revise", "Reject"
    revised_deduction: Optional[float]
    final_deduction: float
    owner_payout_amount: float
    renter_refund_amount: float

    arbitration_dossier: Optional[Dict[str, Any]]
    audit_trail: List[Dict[str, Any]]
    error_message: Optional[str]
